"""iiko mvp tables"""
from alembic import op
import sqlalchemy as sa
revision='0002_iiko_mvp'
down_revision='0001_initial_schema'
branch_labels=None
depends_on=None

def upgrade():
    op.create_table('iiko_restaurants', sa.Column('id', sa.Integer, primary_key=True), sa.Column('name', sa.String(200), nullable=False), sa.Column('code', sa.String(120), nullable=False, unique=True), sa.Column('city', sa.String(120)), sa.Column('email_alias', sa.String(255)), sa.Column('subject_code', sa.String(120)), sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')), sa.Column('created_at', sa.DateTime()))
    op.create_table('restaurant_bots', sa.Column('id', sa.Integer, primary_key=True), sa.Column('restaurant_id', sa.Integer, sa.ForeignKey('iiko_restaurants.id')), sa.Column('bot_token', sa.String(255)), sa.Column('telegram_chat_id', sa.String(120)), sa.Column('bot_username', sa.String(120)), sa.Column('is_active', sa.Boolean()), sa.Column('created_at', sa.DateTime()))
    op.create_table('report_types', sa.Column('id', sa.Integer, primary_key=True), sa.Column('report_code', sa.String(10), unique=True), sa.Column('report_name_ru', sa.String(200)), sa.Column('iiko_report_name', sa.String(255)), sa.Column('frequency', sa.String(50)), sa.Column('is_active', sa.Boolean()));
    op.create_table('report_imports', sa.Column('id', sa.Integer, primary_key=True), sa.Column('restaurant_id', sa.Integer, sa.ForeignKey('iiko_restaurants.id')), sa.Column('report_type', sa.String(20)), sa.Column('report_date', sa.Date()), sa.Column('source', sa.String(30)), sa.Column('email_subject', sa.String(500)), sa.Column('email_from', sa.String(255)), sa.Column('email_message_id', sa.String(255)), sa.Column('original_filename', sa.String(255)), sa.Column('stored_file_path', sa.String(500)), sa.Column('status', sa.String(20)), sa.Column('error_message', sa.Text()), sa.Column('raw_metadata', sa.JSON()), sa.Column('created_at', sa.DateTime()), sa.Column('processed_at', sa.DateTime()))
    op.create_table('sales_daily', sa.Column('id', sa.Integer, primary_key=True), sa.Column('restaurant_id', sa.Integer, sa.ForeignKey('iiko_restaurants.id')), sa.Column('report_import_id', sa.Integer, sa.ForeignKey('report_imports.id')), sa.Column('business_date', sa.Date()), sa.Column('revenue_total', sa.Numeric(14,2)), sa.Column('orders_count', sa.Integer), sa.Column('guests_count', sa.Integer), sa.Column('average_check', sa.Numeric(12,2)), sa.Column('raw_data', sa.JSON()), sa.Column('created_at', sa.DateTime()))
    op.create_table('purchase_price_events', sa.Column('id', sa.Integer, primary_key=True), sa.Column('restaurant_id', sa.Integer, sa.ForeignKey('iiko_restaurants.id')), sa.Column('report_import_id', sa.Integer, sa.ForeignKey('report_imports.id')), sa.Column('product_name', sa.String(250)), sa.Column('product_code', sa.String(120)), sa.Column('arrival_datetime', sa.DateTime()), sa.Column('supplier_name', sa.String(250)), sa.Column('invoice_number', sa.String(120)), sa.Column('supplier_product_name', sa.String(250)), sa.Column('unit', sa.String(50)), sa.Column('price_with_vat', sa.Numeric(12,2)), sa.Column('unit_price_with_vat', sa.Numeric(12,2)), sa.Column('pricelist_price', sa.Numeric(12,2)), sa.Column('price_deviation_rub', sa.Numeric(12,2)), sa.Column('price_deviation_percent', sa.Numeric(8,2)), sa.Column('raw_data', sa.JSON()), sa.Column('created_at', sa.DateTime()));
    op.create_table('purchase_items', sa.Column('id', sa.Integer, primary_key=True), sa.Column('restaurant_id', sa.Integer, sa.ForeignKey('iiko_restaurants.id')), sa.Column('report_import_id', sa.Integer, sa.ForeignKey('report_imports.id')), sa.Column('business_date', sa.Date()), sa.Column('supplier_name', sa.String(200)), sa.Column('invoice_number', sa.String(100)), sa.Column('product_name', sa.String(250)), sa.Column('price', sa.Numeric(12,2)), sa.Column('amount', sa.Numeric(12,2)), sa.Column('raw_data', sa.JSON()), sa.Column('created_at', sa.DateTime()))
    op.create_table('movement_items', sa.Column('id', sa.Integer, primary_key=True), sa.Column('restaurant_id', sa.Integer, sa.ForeignKey('iiko_restaurants.id')), sa.Column('report_import_id', sa.Integer, sa.ForeignKey('report_imports.id')), sa.Column('business_date', sa.Date()), sa.Column('product_name', sa.String(250)), sa.Column('operation_type', sa.String(120)), sa.Column('document_type', sa.String(120)), sa.Column('amount', sa.Numeric(12,2)), sa.Column('is_writeoff', sa.Boolean()), sa.Column('raw_data', sa.JSON()), sa.Column('created_at', sa.DateTime()))
    op.create_table('osv_items', sa.Column('id', sa.Integer, primary_key=True), sa.Column('restaurant_id', sa.Integer, sa.ForeignKey('iiko_restaurants.id')), sa.Column('report_import_id', sa.Integer, sa.ForeignKey('report_imports.id')), sa.Column('business_date', sa.Date()), sa.Column('product_name', sa.String(250)), sa.Column('quantity', sa.Numeric(12,3)), sa.Column('amount', sa.Numeric(12,2)), sa.Column('is_negative', sa.Boolean()), sa.Column('raw_data', sa.JSON()), sa.Column('created_at', sa.DateTime()))
    op.create_table('alerts', sa.Column('id', sa.Integer, primary_key=True), sa.Column('restaurant_id', sa.Integer, sa.ForeignKey('iiko_restaurants.id')), sa.Column('severity', sa.String(20)), sa.Column('alert_type', sa.String(80)), sa.Column('title', sa.String(200)), sa.Column('message', sa.Text()), sa.Column('data', sa.JSON()), sa.Column('is_sent', sa.Boolean()), sa.Column('created_at', sa.DateTime()), sa.Column('sent_at', sa.DateTime()))
    op.create_table('dashboard_snapshots', sa.Column('id', sa.Integer, primary_key=True), sa.Column('restaurant_id', sa.Integer, sa.ForeignKey('iiko_restaurants.id')), sa.Column('business_date', sa.Date()), sa.Column('revenue_total', sa.Numeric(14,2)), sa.Column('purchases_total', sa.Numeric(14,2)), sa.Column('writeoffs_total', sa.Numeric(14,2)), sa.Column('writeoffs_percent', sa.Numeric(8,2)), sa.Column('negative_stock_count', sa.Integer), sa.Column('purchase_price_risks_count', sa.Integer), sa.Column('status', sa.String(20)), sa.Column('data', sa.JSON()), sa.Column('created_at', sa.DateTime()))

def downgrade():
    for t in ['dashboard_snapshots','purchase_price_events','report_types','alerts','osv_items','movement_items','purchase_items','sales_daily','report_imports','restaurant_bots','iiko_restaurants']:
        op.drop_table(t)
